# Generated by Django 4.2.1 on 2023-05-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_purchase_company_alter_purchase_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='totalPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
