# Generated by Django 4.2.1 on 2023-06-20 05:58

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_stock_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='provider',
        ),
        migrations.AddField(
            model_name='product',
            name='lowStockLimit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='unit',
            field=models.CharField(choices=[('kg', 'KG'), ('litre', 'Litre'), ('piece', 'Piece'), ('feet', 'Feet')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saledetail',
            name='unit',
            field=models.CharField(choices=[('kg', 'KG'), ('litre', 'Litre'), ('piece', 'Piece'), ('feet', 'Feet')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='salePrice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='unit',
            field=models.CharField(choices=[('kg', 'KG'), ('litre', 'Litre'), ('piece', 'Piece'), ('feet', 'Feet')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.supplier'),
            preserve_default=False,
        ),
    ]
