# Generated by Django 4.2.1 on 2023-06-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_amount_refund_unitprice_refund_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sold',
            field=models.IntegerField(default=0),
        ),
    ]
