# Generated by Django 4.2.1 on 2023-06-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_stock_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paid',
            field=models.FloatField(default=0),
        ),
    ]
