# Generated by Django 4.2.1 on 2023-06-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sale_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='discount',
            new_name='discountAmount',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='paid',
            new_name='paidAmount',
        ),
        migrations.AddField(
            model_name='sale',
            name='changeAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('refund', 'Refunded')], max_length=20),
        ),
    ]
