# Generated by Django 4.2.1 on 2023-07-08 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_totalprice_refund_totalrefund_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duecollection',
            old_name='Amount',
            new_name='amount',
        ),
    ]
