# Generated by Django 4.2.1 on 2023-06-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_saledetail_refund_saledetail_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='Amount',
            new_name='unitPrice',
        ),
        migrations.AddField(
            model_name='refund',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='saleDetail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.saledetail'),
            preserve_default=False,
        ),
    ]
