# Generated by Django 4.2.1 on 2023-07-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_discount_sale_discountamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='totalPrice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
